/**
 * R tools - syntax checking and optional execution
 */

export interface RIssue {
  type: 'error' | 'warning';
  line?: number;
  message: string;
}

export class RTools {
  /**
   * Run basic syntax checks on R code
   */
  static checkSyntax(code: string): RIssue[] {
    const issues: RIssue[] = [];
    const lines = code.split('\n');

    let parenDepth = 0;
    let braceDepth = 0;
    let bracketDepth = 0;

    lines.forEach((line, idx) => {
      const lineNum = idx + 1;

      // Skip comments
      const commentIndex = line.indexOf('#');
      const codePart = commentIndex >= 0 ? line.substring(0, commentIndex) : line;

      // Check for balanced delimiters
      for (const char of codePart) {
        if (char === '(') parenDepth++;
        if (char === ')') parenDepth--;
        if (char === '{') braceDepth++;
        if (char === '}') braceDepth--;
        if (char === '[') bracketDepth++;
        if (char === ']') bracketDepth--;

        if (parenDepth < 0) {
          issues.push({
            type: 'error',
            line: lineNum,
            message: 'Unmatched closing parenthesis'
          });
          parenDepth = 0; // Reset to avoid cascading errors
        }
      }

      // Check for assignment operators
      if (codePart.includes('=') && !codePart.match(/[<>!=]=/) && !codePart.includes('==')) {
        if (!codePart.includes('function') && !codePart.includes('for') && !codePart.includes('if')) {
          issues.push({
            type: 'warning',
            line: lineNum,
            message: 'Consider using <- instead of = for assignment (R convention)'
          });
        }
      }

      // Check for common mistakes
      if (codePart.includes('T') && codePart.match(/\bT\b/) && !codePart.includes('TRUE')) {
        issues.push({
          type: 'warning',
          line: lineNum,
          message: 'Use TRUE instead of T for better clarity'
        });
      }

      if (codePart.includes('F') && codePart.match(/\bF\b/) && !codePart.includes('FALSE')) {
        issues.push({
          type: 'warning',
          line: lineNum,
          message: 'Use FALSE instead of F for better clarity'
        });
      }
    });

    // Final checks
    if (parenDepth > 0) {
      issues.push({
        type: 'error',
        message: `${parenDepth} unclosed parenthes${parenDepth === 1 ? 'is' : 'es'}`
      });
    }

    if (braceDepth > 0) {
      issues.push({
        type: 'error',
        message: `${braceDepth} unclosed brace${braceDepth === 1 ? '' : 's'}`
      });
    }

    if (bracketDepth > 0) {
      issues.push({
        type: 'error',
        message: `${bracketDepth} unclosed bracket${bracketDepth === 1 ? '' : 's'}`
      });
    }

    return issues;
  }

  /**
   * Extract required packages from R code
   */
  static extractPackages(code: string): string[] {
    const packages: string[] = [];
    const libraryRegex = /library\(([^)]+)\)/g;
    const requireRegex = /require\(([^)]+)\)/g;

    let match;
    while ((match = libraryRegex.exec(code)) !== null) {
      packages.push(match[1].replace(/['"]/g, ''));
    }

    while ((match = requireRegex.exec(code)) !== null) {
      packages.push(match[1].replace(/['"]/g, ''));
    }

    return [...new Set(packages)]; // Remove duplicates
  }

  /**
   * Add comments and structure to R code
   */
  static addDocumentation(code: string, description?: string): string {
    const header = `#' ${description || 'R Script for Economics Course'}
#'
#' This script is part of the course materials.
#' Dependencies: ${this.extractPackages(code).join(', ') || 'base R'}
#'
#' @author Generated by Economics Teaching Assistant
#' @date ${new Date().toISOString().split('T')[0]}

`;

    return header + code;
  }

  /**
   * Check for minimal dependencies requirement
   */
  static checkDependencies(code: string): { minimal: boolean; packages: string[]; suggestions: string[] } {
    const packages = this.extractPackages(code);
    const suggestions: string[] = [];

    // Common heavy packages that might have lighter alternatives
    const heavyPackages = ['tidyverse', 'ggplot2'];
    const foundHeavy = packages.filter(p => heavyPackages.includes(p));

    if (foundHeavy.length > 0) {
      suggestions.push(`Consider if all features of ${foundHeavy.join(', ')} are needed`);
    }

    return {
      minimal: foundHeavy.length === 0,
      packages,
      suggestions
    };
  }
}
